### ISSUE TITLE
The pipeline BOSH create release needs to correctly use the BOSH CLI

### ISSUE THREAD

**Issue by maximilien** [cloudfoundry-community/bosh-softlayer-tools#13]
The current pipeline stage to create the BOSH CPI release tarball should use the BOSH `create release` command, documented [here](http://cloudfoundryjp.github.io/docs/running/bosh/reference/bosh-cli.html).

**Comment by maximilien** [comment]
@posijon I am assigning this to you in case you have some time to fix, otherwise, I will take it over.

It should be relatively easy change, except you will need to add the BOSH CLI into the docker image so you can use it to issue the `create release` command.

Thanks.

**Comment by jlo** [comment]
@maximilien Do you mean I should change the script here https://github.com/maximilien/bosh-softlayer-cpi-release/blob/master/ci/scripts/shipit to use the bosh `create release` command instead of archiving the project? If so, I tried running `bosh create release` on the project locally and it seems to be unable to find the golang_1.3 package. Can you confirm?
I'm not sure where it looks for this as I can't find it in the warden cpi release either.

**Comment by maximilien** [comment]
Yup, @posijon, we need to use the `bosh create release` command since I believe it adds metadata and does checks when creating the tarball.

Let's change the Golang version if it needs it. Thanks,

Max

**Comment by maximilien** [comment]
Where you able to switch to `bosh create release` instead of a simple tarball?

**Comment by jlo** [comment]
Hey I haven't done it yet

**Comment by maximilien** [comment]
OK cool, Thanks. Maybe we'll take it from there. See you tomorrow. Cheers.

**Comment by maximilien** [comment]
@posijon and @swetharepakula, closing this since I believe you have fixed it?
